import { View, Text, StyleSheet, TextInput, TouchableOpacity, KeyboardAvoidingView, Platform } from 'react-native';
import { useState, useEffect } from 'react';
import { LinearGradient } from 'expo-linear-gradient';
import { Moon, Lock, CircleCheck as CheckCircle, TriangleAlert, Eye, EyeOff } from 'lucide-react-native';
import { useRouter, useLocalSearchParams } from 'expo-router';
import { useLanguage } from '@/contexts/LanguageContext';
import { supabase, SUPABASE_URL, SUPABASE_ANON_KEY } from '@/lib/supabase';

export default function ResetPasswordScreen() {
  const pickParam = (value?: string | string[]) =>
    Array.isArray(value) ? value[0] : value;

  const [password, setPassword] = useState('');
  const [confirm, setConfirm] = useState('');
  const [showPassword, setShowPassword] = useState(false);
  const [loading, setLoading] = useState(false);
  const [done, setDone] = useState(false);
  const [errorMsg, setErrorMsg] = useState('');
  const [recoveryReady, setRecoveryReady] = useState(false);
  const [initializingRecovery, setInitializingRecovery] = useState(true);
  const { token, access_token, refresh_token, code, token_hash, type } = useLocalSearchParams<{
    token?: string;
    access_token?: string;
    refresh_token?: string;
    code?: string;
    token_hash?: string;
    type?: string;
  }>();
  const router = useRouter();
  const { t } = useLanguage();
  const legacyToken = pickParam(token);

  useEffect(() => {
    let mounted = true;

    const initRecoverySession = async () => {
      // Legacy links generated by old custom function still use ?token=
      if (legacyToken) {
        if (mounted) setRecoveryReady(true);
        if (mounted) setInitializingRecovery(false);
        return;
      }

      let accessToken = pickParam(access_token);
      let refreshToken = pickParam(refresh_token);
      let authCode = pickParam(code);
      let tokenHash = pickParam(token_hash);
      let otpType = pickParam(type);

      // Supabase recovery on web commonly arrives in URL hash fragment.
      if (Platform.OS === 'web' && typeof window !== 'undefined') {
        const searchParams = new URLSearchParams(window.location.search || '');
        const hash = window.location.hash?.startsWith('#') ? window.location.hash.slice(1) : '';
        accessToken = accessToken || searchParams.get('access_token') || undefined;
        refreshToken = refreshToken || searchParams.get('refresh_token') || undefined;
        authCode = authCode || searchParams.get('code') || undefined;
        tokenHash = tokenHash || searchParams.get('token_hash') || undefined;
        otpType = otpType || searchParams.get('type') || undefined;
        if (hash) {
          const hashParams = new URLSearchParams(hash);
          accessToken = accessToken || hashParams.get('access_token') || undefined;
          refreshToken = refreshToken || hashParams.get('refresh_token') || undefined;
          authCode = authCode || hashParams.get('code') || undefined;
          tokenHash = tokenHash || hashParams.get('token_hash') || undefined;
          otpType = otpType || hashParams.get('type') || undefined;
        }
      }

      const hasRecoveryParams = Boolean(accessToken || refreshToken || authCode || tokenHash || otpType);

      if (accessToken && refreshToken) {
        const { error } = await supabase.auth.setSession({
          access_token: accessToken,
          refresh_token: refreshToken,
        });
        if (!mounted) return;
        if (!error) {
          setRecoveryReady(true);
          setInitializingRecovery(false);
          return;
        }
      }

      if (authCode) {
        const { error } = await supabase.auth.exchangeCodeForSession(authCode);
        if (!mounted) return;
        if (!error) {
          setRecoveryReady(true);
          setInitializingRecovery(false);
          return;
        }
      }

      if (tokenHash && otpType) {
        const { error } = await supabase.auth.verifyOtp({
          token_hash: tokenHash,
          type: otpType as any,
        });
        if (!mounted) return;
        if (!error) {
          setRecoveryReady(true);
          setInitializingRecovery(false);
          return;
        }
      }

      if (mounted) {
        // If we at least got recovery params, keep the form available and let
        // updateUser report the concrete error instead of failing early.
        if (hasRecoveryParams) {
          setRecoveryReady(true);
          setErrorMsg('');
        } else {
          setErrorMsg(t('auth.reset.errorInvalid'));
        }
        setInitializingRecovery(false);
      }
    };

    initRecoverySession();
    return () => {
      mounted = false;
    };
  }, [legacyToken, access_token, refresh_token, code, token_hash, type, t]);

  const handleReset = async () => {
    setErrorMsg('');
    if (!password) {
      setErrorMsg(t('auth.reset.errorEmpty'));
      return;
    }
    if (password.length < 6) {
      setErrorMsg(t('auth.reset.errorShort'));
      return;
    }
    if (password !== confirm) {
      setErrorMsg(t('auth.reset.errorMismatch'));
      return;
    }

    setLoading(true);
    try {
      if (legacyToken) {
        // Backward compatibility for old reset links.
        const res = await fetch(`${SUPABASE_URL}/functions/v1/reset-password`, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${SUPABASE_ANON_KEY}`,
          },
          body: JSON.stringify({ token: legacyToken, password }),
        });
        const data = await res.json();
        if (!res.ok || data.error) {
          setErrorMsg(data.error || t('auth.reset.errorSave'));
        } else {
          setDone(true);
        }
      } else {
        const { error } = await supabase.auth.updateUser({ password });
        if (error) {
          setErrorMsg(error.message || t('auth.reset.errorSave'));
        } else {
          setDone(true);
        }
      }
    } catch {
      setErrorMsg(t('auth.reset.errorGeneric'));
    } finally {
      setLoading(false);
    }
  };

  return (
    <KeyboardAvoidingView
      style={styles.container}
      behavior={Platform.OS === 'ios' ? 'padding' : 'height'}
    >
      <LinearGradient colors={['#07070f', '#0d0d16']} style={styles.gradient}>
        <View style={styles.content}>
          <View style={styles.header}>
            <Moon size={56} color="#d4a96a" />
            <Text style={styles.appName}>GoZzzz</Text>
          </View>

          {done ? (
            <View style={styles.successContainer}>
              <CheckCircle size={56} color="#d4a96a" style={styles.successIcon} />
              <Text style={styles.successTitle}>{t('auth.reset.successTitle')}</Text>
              <Text style={styles.successMessage}>
                {t('auth.reset.successMsg')}
              </Text>
              <TouchableOpacity style={styles.loginButton} onPress={() => router.replace('/(auth)/login')}>
                <Text style={styles.loginButtonText}>{t('auth.reset.successButton')}</Text>
              </TouchableOpacity>
            </View>
          ) : (
            <View style={styles.form}>
              <Text style={styles.formTitle}>Nova senha</Text>
              <Text style={styles.formSubtitle}>Escolha uma senha segura para sua conta.</Text>

              {errorMsg ? (
                <View style={styles.errorBanner}>
                  <TriangleAlert size={16} color="#ef4444" />
                  <Text style={styles.errorBannerText}>{errorMsg}</Text>
                </View>
              ) : null}

              <View style={styles.inputContainer}>
                <View style={styles.inputIcon}>
                  <Lock size={20} color="#d4a96a" />
                </View>
                <TextInput
                  style={styles.input}
                  placeholder="Nova senha"
                  placeholderTextColor="#5a5a6a"
                  value={password}
                  onChangeText={(v) => { setErrorMsg(''); setPassword(v); }}
                  secureTextEntry={!showPassword}
                  autoCapitalize="none"
                />
                <TouchableOpacity onPress={() => setShowPassword(!showPassword)} style={styles.eyeButton}>
                  {showPassword ? <EyeOff size={20} color="#5a5a6a" /> : <Eye size={20} color="#5a5a6a" />}
                </TouchableOpacity>
              </View>

              <View style={styles.inputContainer}>
                <View style={styles.inputIcon}>
                  <Lock size={20} color="#d4a96a" />
                </View>
                <TextInput
                  style={styles.input}
                  placeholder="Confirmar nova senha"
                  placeholderTextColor="#5a5a6a"
                  value={confirm}
                  onChangeText={(v) => { setErrorMsg(''); setConfirm(v); }}
                  secureTextEntry={!showPassword}
                  autoCapitalize="none"
                />
              </View>

              <TouchableOpacity
                style={[styles.submitButton, (loading || initializingRecovery || (!legacyToken && !recoveryReady)) && styles.submitButtonDisabled]}
                onPress={handleReset}
                disabled={loading || initializingRecovery || (!legacyToken && !recoveryReady)}
              >
                <Text style={styles.submitButtonText}>
                  {loading ? t('auth.reset.saving') : t('auth.reset.btnSave')}
                </Text>
              </TouchableOpacity>
            </View>
          )}
        </View>
      </LinearGradient>
    </KeyboardAvoidingView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1 },
  gradient: { flex: 1 },
  content: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 80,
    paddingBottom: 40,
  },
  header: {
    alignItems: 'center',
    marginBottom: 48,
  },
  appName: {
    fontSize: 36,
    fontWeight: '800',
    color: '#ffffff',
    marginTop: 12,
  },
  form: {
    flex: 1,
    justifyContent: 'center',
  },
  formTitle: {
    fontSize: 28,
    fontWeight: '800',
    color: '#ffffff',
    marginBottom: 12,
    textAlign: 'center',
  },
  formSubtitle: {
    fontSize: 15,
    color: '#8892a4',
    textAlign: 'center',
    lineHeight: 23,
    marginBottom: 32,
    fontWeight: '500',
  },
  errorBanner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
    borderRadius: 10,
    padding: 12,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.25)',
  },
  errorBannerText: {
    flex: 1,
    fontSize: 14,
    color: '#ef4444',
    fontWeight: '500',
    lineHeight: 20,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(212, 169, 106, 0.08)',
    borderRadius: 12,
    marginBottom: 16,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: 'rgba(212, 169, 106, 0.2)',
  },
  inputIcon: { marginRight: 12 },
  input: {
    flex: 1,
    paddingVertical: 16,
    fontSize: 16,
    color: '#ffffff',
    fontWeight: '500',
  },
  eyeButton: { padding: 4 },
  submitButton: {
    backgroundColor: '#d4a96a',
    borderRadius: 12,
    paddingVertical: 18,
    alignItems: 'center',
    marginTop: 8,
    shadowColor: '#d4a96a',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 5,
  },
  submitButtonDisabled: { opacity: 0.6 },
  submitButtonText: {
    fontSize: 17,
    fontWeight: '700',
    color: '#09061a',
  },
  successContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  successIcon: { marginBottom: 24 },
  successTitle: {
    fontSize: 28,
    fontWeight: '800',
    color: '#ffffff',
    marginBottom: 16,
    textAlign: 'center',
  },
  successMessage: {
    fontSize: 15,
    color: '#8892a4',
    textAlign: 'center',
    lineHeight: 24,
    marginBottom: 40,
    fontWeight: '500',
  },
  loginButton: {
    backgroundColor: '#d4a96a',
    borderRadius: 12,
    paddingVertical: 16,
    paddingHorizontal: 48,
    shadowColor: '#d4a96a',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 5,
  },
  loginButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#09061a',
  },
});
